### ISSUE TITLE
karray2d_row argument receives wrong values when passed a sliced numpy array through python bindings

### ISSUE THREAD

**Issue by egstern** [fnalacceleratormodeling/synergia2#250] opened 2024-04-05 01:20 UTC
Routine Lattice_simulator::map_to_twiss(karray_2d map) takes a 2x2 array as an argument. When I pass a sliced numpy array into the routine, the values it receives are the wrong ones.

### define arr1
```
arr1 = np.array([[11, 12, 13, 14, 15, 16],
                 [21, 22, 23, 24, 25, 26],
                 [31, 32, 33, 34, 35, 36],
                 [41, 42, 43, 44, 45, 46],
                 [51, 52, 53, 54, 55, 56],
                 [61, 62, 63, 64, 65, 66]])
```

### pass `arr1[4:6, 4:6]` to map_to_twiss, adding debug printout reveals that the routine receives elements
```
    [[55, 56]
     [61, 62]]
```

instead of what it should get which is
```
    [[55, 56]
     [65, 66]]
```

**Comment by s-sajid-ali** [comment] 2024-04-09 22:42
The issue is probably from the fact that the sliced array does not have contiguous memory:
```
>>> import numpy as np;arr1 = np.array([[11, 12, 13, 14, 15, 16],[21, 22, 23, 24, 25, 26],[31, 32, 33, 34, 35, 36],[41, 42, 43, 44, 45, 46],              [51, 52, 53, 54, 55, 56],[61, 62, 63, 64, 65, 66]])
>>> arr1.flags
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

>>> arr1[4:6,4:6].flags
  C_CONTIGUOUS : False
  F_CONTIGUOUS : False
  OWNDATA : False
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

>>> 
```
But, the function `map_to_twiss` assumes that it is contiguous as it creates the Kokkos view from the pointer of the sliced array without allocating any new memory
https://github.com/fnalacceleratormodeling/synergia2/blob/f33b83c72c64382d8ef6098445e1817e31533e52/src/synergia/simulation/simulation_pywrap.cc#L309-L317

Since this is a small 2x2 array, the easiest fix would be change `map_to_twiss` to create a kokkos-owned 2D array and copy the elements one at a time. I'll put in the fix shortly.

**Comment by s-sajid-ali** [comment] 2024-04-12 21:13
Fixed by https://github.com/fnalacceleratormodeling/synergia2/pull/251

**Closed as completed** 2024-04-12 21:13 UTC
